# This code is part of Qiskit.
#
# (C) Copyright IBM 2018, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

notifications:
  email: false

cache:
  pip: true
  directories:
    - .stestr
os: linux
dist: xenial

language: python
python: 3.7

git:
  depth: false

env:
  global:
    - DEPENDENCY_BRANCH=$(if [[ "$TRAVIS_BRANCH" == stable* ]]; then echo "stable"; else echo "master"; fi)
    - INIT_FILE="$TRAVIS_BUILD_DIR/qiskit/__init__.py"

stage_dependencies: &stage_dependencies
  before_install:
    - |
      if [ -f $INIT_FILE ]; then
        # stops travis if __init__.py exists under qiskit
        echo "File '$INIT_FILE' found. It should not exist, since this repo extends qiskit namespace.";
        travis_terminate 1;
      fi
    - |
      if [ "$INSTALL_PSI4" == "yes" ]; then
        # Download and install miniconda psi4
        wget http://vergil.chemistry.gatech.edu/psicode-download/Psi4conda-1.3.2-py37-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda activate
      fi
    - pip install -U 'pip<20.0.0'
    - pip install -U setuptools wheel
    - |
      if [ "$DEPENDENCY_BRANCH" == "master" ]; then
        pip install cython
        # Installing qiskit-terra master branch...
        pip install https://github.com/Qiskit/qiskit-terra/archive/master.zip --progress-bar off
        # Installing qiskit-ignis master branch...
        pip install https://github.com/Qiskit/qiskit-ignis/archive/master.zip --progress-bar off
        # Installing qiskit-ibmq-provider master branch...
        pip install https://github.com/Qiskit/qiskit-ibmq-provider/archive/master.zip --progress-bar off
        # install qiskit-aer build dependencies
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt-get -y install g++-7
        sudo apt-get -y install libopenblas-dev
        # Clone qiskit-aer
        git clone --recurse-submodules https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
        cd /tmp/qiskit-aer
        # Install qiskit-aer requirements.
        pip install -U -c constraints.txt -r requirements-dev.txt --progress-bar off
        # Build qiskit-aer with Thrust OpenMP CPU backend
        python setup.py bdist_wheel -- -DCMAKE_CXX_COMPILER=g++-7 -DAER_THRUST_BACKEND=OMP -- -j4
        pip install dist/qiskit_aer*whl
        # back to current repo directory
        cd $TRAVIS_BUILD_DIR
      fi
    # install Aqua and Aqua dev. requirements
    - pip install -e $TRAVIS_BUILD_DIR --progress-bar off
    - pip install -U -c constraints.txt -r requirements-dev.txt --progress-bar off
    - |
      if [ "$DEPENDENCY_BRANCH" != "master" ]; then
        pip install qiskit-ibmq-provider
      fi

stage_test_aqua: &stage_test_aqua
  <<: *stage_dependencies
  install:
    - |
      cat > selection.txt <<EOF
      test.aqua.operators.test_tpb_grouped_weighted_pauli_operator
      test.aqua.operators.test_weighted_pauli_operator
      test.aqua.test_custom_circuit_oracle
      test.aqua.test_entangler_map
      test.aqua.test_eoh
      test.aqua.test_fixed_value_comparator
      test.aqua.test_hhl
      test.aqua.test_initial_state_custom
      test.aqua.test_initial_state_zero
      test.aqua.test_iqpe
      test.aqua.test_logical_expression_oracle
      test.aqua.test_lookup_rotation
      test.aqua.test_measure_error_mitigation
      test.aqua.test_nlopt_optimizers
      test.aqua.test_numpy_eigen_solver
      test.aqua.test_numpy_ls_solver
      test.aqua.test_optimizers
      test.aqua.test_qgan
      test.aqua.test_qpe
      test.aqua.test_qsvm
      test.aqua.test_rmg
      test.aqua.test_ry
      test.aqua.test_shor
      test.aqua.test_simon
      EOF

jobs:
  include:
    - stage: Checks and Tests
      <<: *stage_dependencies
      name: "Spell, Style, Lint, Docs check"
      if: tag IS blank
      install:
        # install spell check libraries
        - sudo apt-get -y install python3-enchant
        - sudo apt-get -y install hunspell-en-us
        - pip install pyenchant
      script:
        - make spell
        - make style
        - make lint
        - make copyright
        - make html SPHINXOPTS=-W
        - make doctest
    - name: "Test Aqua 1 Python 3.7"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua137
          paths:
            - aqua1.dat
            - aqua137.dep
      before_script:
        - pip install cvxopt
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/aqua run --blacklist-file selection.txt 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage aqua1.dat
        - python tools/extract_deprecation.py -file out.txt -output aqua137.dep
    - name: "Test Aqua 1 Python 3.8"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua138
          paths: aqua138.dep
      python: 3.8
      before_script:
        - pip install cvxopt
      script:
        - stestr --test-path test/aqua run --blacklist-file selection.txt 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output aqua138.dep
    - name: "Test Aqua 2 Python 3.7"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua237
          paths:
            - aqua2.dat
            - aqua237.dep
      before_script:
        - pip install cvxopt
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/aqua run --whitelist-file selection.txt 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage aqua2.dat
        - python tools/extract_deprecation.py -file out.txt -output aqua237.dep
    - name: "Test Aqua 2 Python 3.8"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua238
          paths: aqua238.dep
      python: 3.8
      before_script:
        - pip install cvxopt
      script:
        - stestr --test-path test/aqua run --whitelist-file selection.txt 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output aqua238.dep
    - name: "Test Chemistry Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      env:
        - INSTALL_PSI4=yes
        - OPENBLAS_NUM_THREADS=1
      workspaces:
        create:
          name: chemistry37
          paths:
            - chemistry.dat
            - chemistry37.dep
      install:
        # install gaussian dependency libgfortran 5
        - sudo apt-get -y update
        - sudo apt-get -y install libgfortran5
        # Installing pyquante2 master branch...
        - pip install https://github.com/rpmuller/pyquante2/archive/master.zip --progress-bar off
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/chemistry run 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage chemistry.dat
        - python tools/extract_deprecation.py -file out.txt -output chemistry37.dep
    - name: "Test Chemistry Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: chemistry38
          paths: chemistry38.dep
      python: 3.8
      env: OPENBLAS_NUM_THREADS=1
      install:
        # install gaussian dependency libgfortran 5
        - sudo apt-get -y update
        - sudo apt-get -y install libgfortran5
        # Installing pyquante2 master branch...
        - pip install https://github.com/rpmuller/pyquante2/archive/master.zip --progress-bar off
      script:
        - stestr --test-path test/chemistry run 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output chemistry38.dep
    - name: "Test Finance Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: finance37
          paths:
            - finance.dat
            - finance37.dep
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/finance run 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage finance.dat
        - python tools/extract_deprecation.py -file out.txt -output finance37.dep
    - name: "Test Finance Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: finance38
          paths: finance38.dep
      python: 3.8
      script:
        - stestr --test-path test/finance run 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output finance38.dep
    - name: "Test Machine Learning Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: ml37
          paths:
            - ml.dat
            - ml37.dep
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/ml run 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage ml.dat
        - python tools/extract_deprecation.py -file out.txt -output ml37.dep
    - name: "Test Machine Learning Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: ml38
          paths: ml38.dep
      python: 3.8
      script:
        - stestr --test-path test/ml run 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output ml38.dep
    - name: "Test Optimization Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: optimization37
          paths:
            - optimization.dat
            - optimization37.dep
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script:
        - stestr --test-path test/optimization run 2> >(tee /dev/stderr out.txt > /dev/null)
        - coverage3 combine
        - mv .coverage optimization.dat
        - python tools/extract_deprecation.py -file out.txt -output optimization37.dep
    - name: "Test Optimization Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: optimization38
          paths: optimization38.dep
      python: 3.8
      script:
        - stestr --test-path test/optimization run 2> >(tee /dev/stderr out.txt > /dev/null)
        - python tools/extract_deprecation.py -file out.txt -output optimization38.dep
    - name: "Run pip check"
      <<: *stage_dependencies
      if: tag IS blank
      script:
        - pip install cvxopt
        - pip install https://github.com/rpmuller/pyquante2/archive/master.zip --progress-bar off
        - pip check
    - stage: Deprecation Messages
      name: "Print deprecation messages"
      if: tag IS blank
      workspaces:
        use:
          - aqua137
          - aqua138
          - aqua237
          - aqua238
          - chemistry37
          - chemistry38
          - finance37
          - finance38
          - ml37
          - ml38
          - optimization37
          - optimization38
      script:
        - sort -f -u aqua137.dep aqua138.dep aqua237.dep aqua238.dep chemistry37.dep chemistry38.dep finance37.dep finance38.dep ml37.dep ml38.dep optimization37.dep optimization38.dep || true
    - stage: Coverage
      name: "Combine all coverages and upload to Coveralls"
      if: tag IS blank
      workspaces:
        use:
          - aqua137
          - aqua237
          - chemistry37
          - finance37
          - ml37
          - optimization37
      install:
        - pip install -U coverage coveralls diff-cover
      script:
        - coverage3 combine aqua1.dat aqua2.dat chemistry.dat finance.dat ml.dat optimization.dat
        - coveralls || true
        - coverage3 xml
        - diff-cover --compare-branch master coverage.xml || true
    - stage: Deploy
      name: "Deploy to Pypi"
      if: tag IS present
      python: 3.7
      env:
        - TWINE_USERNAME=qiskit
      install:
        - pip install -U twine pip setuptools virtualenv wheel
      script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/qiskit*
